language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-unicorn.gemspec
- gem install sensu-plugins-unicorn-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: TY9BnFHi6T2yYtExEGmL4KSdGQQuWj2ZSVDnuv6z8fmMjarFYWU7gqdyVmlrmH0JQFRkFJrUIUULIX6bVH2B+qaEUc8DaBxbDonuI07+y/E4WEuch+YKL9VvAfoBmMxXFhSwL2JbOZswyRjv2RRzzRKiWe2LxA3Honrpe5xd75Q=
  gem: sensu-plugins-unicorn
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-unicorn
